# Grafana with provisioning
FROM grafana/grafana:latest

# Grafana provisioning is handled via volume mounts
# Any additional plugins or configs can be added here
# COPY docker_configs/grafana/custom/ /etc/grafana/

USER grafana

