# Caddy reverse proxy
FROM caddy:latest

# Caddyfile is provided via volume mount
# Any additional Caddy modules or plugins can be installed here if needed
# RUN caddy add-package <module>

USER caddy

